insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Ulefone Armor 2', 40517.89, 0.5, 'Android 7.0', 5, 'LG Univa E510', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BlackBerry Curve 8330', 67186.78, 0.4, 'BlackBerry OS', 3, 'HP Pro Slate 8', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Micromax X266', 16157.31, 0.4, 'Feature phone', 1, 'Plum Trigger Plus', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung I9100G Galaxy S II', 47216.94, 0.4, 'Android 2.3.4, 4.0.4, up to 4.1.2', 1, 'Oppo A53 5G', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG Fantasy E740', 54287.05, 0.1, 'Microsoft Windows Phone 7', 3, 'Celkon C6 Star', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Xiaomi Mi Note 2', 35925.2, 0.2, 'Android 6.0, MIUI 8.2', 3, 'Lenovo K6', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung I8520 Galaxy Beam', 28343.54, 0.5, 'Android 2.1', 1, 'LG G7020', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Bird M01', 16457.69, 0.2, 'Feature phone', 3, 'Tecno Spark 3 Pro', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung L600', 49325.41, 0.2, 'Feature phone', 5, 'ZTE Axon Max', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Amazon Kindle Fire', 32736.75, 0.2, 'Android 2.3', 1, 'Nokia 5100', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BlackBerry 7130v', 31712.15, 0.2, 'BlackBerry OS', 1, 'Samsung Galaxy Tab 4 7.0 LTE', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Celkon CT-888', 15511.39, 0.4, 'Android 4.0.4', 2, 'O2 XDA Orbit', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung S5200', 49124.22, 0.5, 'Feature phone', 2, 'Samsung I405 Stratosphere', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('HTC Touch HD', 52631.62, 0.3, 'Microsoft Windows Mobile 6.1 Professional', 2, 'Philips 535', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sony Xperia M5 Dual', 11644.48, 0.1, 'Android 5.0, up to 5.1', 5, 'Samsung T249', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung X200', 66818.95, 0.4, 'Feature phone', 2, 'i-mate PDA2', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('QMobile B800', 53146.2, 0.3, 'Feature phone', 3, 'Gionee M12', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Amazon Kindle Fire HDX 8.9', 57451.99, 0.2, 'Android OS, Fire 3', 2, 'Toshiba Excite Go', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('QMobile Noir X90', 37174.64, 0.2, 'Android 4.4.2', 4, 'HTC HD2', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Motorola GLEAM', 52886.33, 0.3, 'Feature phone', 1, 'Samsung E1125', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Ericsson A2618', 25072.04, 0.3, 'Feature phone', 1, 'Orange San Francisco', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('NEC e808', 60522.96, 0.3, 'Feature phone', 4, 'Google Pixel 3', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy S5 Sport', 22413.2, 0.5, 'Android 4.4.2, up to 6.0, TouchWiz UI', 1, 'Samsung ZV10', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('alcatel OT-385', 62907.66, 0.4, 'Feature phone', 4, 'ZTE Blade 10 Prime', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('HTC Desire VT', 51175.38, 0.1, 'Android 4.0, Sense UI 4', 3, 'LG KU970 Shine', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Acer beTouch E100', 40010.96, 0.3, 'Microsoft Windows Mobile 6.5 Professional', 5, 'Prestigio MultiPad 2 Prime Duo 8.0', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sony Xperia Z5 Dual', 50606.13, 0.2, 'Android 5.1.1, up to 7.0', 5, 'Ulefone T2', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Yezz Andy 5EI3 (2016)', 68448.68, 0.1, 'Android 6.0', 1, 'vivo iQOO U1', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Kyocera DuraForce', 32274.5, 0.4, 'Android 4.4.2', 1, 'alcatel Pixi 3 (7) LTE', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Nokia 112', 50624.08, 0.5, 'Feature phone', 3, 'Wiko Sunny', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Micromax Q55 Bling', 27375.95, 0.4, 'Feature phone', 1, 'Philips 160', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Plum Gator 5', 31730.33, 0.2, 'Android 8.1', 4, 'BLU Studio 5.0 CE', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('vivo V7+', 11360.36, 0.1, 'Android 7.1.2, Funtouch 3.2', 5, 'Xiaomi Redmi 5A', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Xiaomi Redmi K30 Pro', 12822.2, 0.5, 'Android 10, MIUI 11', 1, 'Xiaomi Mi 2S', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('YU Yunique Plus', 60480.21, 0.1, 'Android 5.1.1', 2, 'Spice D-1111', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Oppo R9s Plus', 23977.15, 0.4, 'Android 6.1, ColorOS 3', 5, 'Micromax X640', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Lenovo Tab 2 A7-20', 18210.49, 0.3, 'Android 4.4, up to 5.0', 4, 'alcatel OT-363', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Yezz Andy A5 1GB', 11391.43, 0.3, 'Android 4.2', 4, 'LG A350', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Wiko Getaway', 20362.94, 0.1, 'Android 4.4.2', 3, 'Samsung Galaxy A7 Duos', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('verykool RS75', 54989.15, 0.5, 'Android 2.3', 1, 'Plum Tag 2 3G', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('T-Mobile Prism', 18421.35, 0.5, 'Android 2.3.5', 3, 'Samsung E1050', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('HTC EVO Shift 4G', 62042.37, 0.1, 'Android 2.2, up to 2.3, Sense UI', 4, 'Sony Xperia E4g Dual', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Xiaomi Mi Watch', 53973.32, 0.4, 'Proprietary OS', 4, 'Micromax X288', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG Univa E510', 66872.95, 0.3, 'Android 2.3', 5, 'Sony Xperia XZ Premium', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Grand X LTE', 30067.52, 0.4, 'Android 7.0', 2, 'Plum Bar 3G', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Plum Galactic', 21810.76, 0.2, 'Feature phone', 2, 'Razer Phone 2', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Tattoo Mini', 49295.07, 0.5, 'Feature phone', 1, 'Lenovo A5000', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Philips F610', 16054.42, 0.3, 'Feature phone', 3, 'Lava X50 Plus', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Microsoft Lumia 640 LTE', 47830.05, 0.1, 'Microsoft Windows Phone 8.1', 4, 'Samsung Galaxy Beam2', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('HTC P3400', 24090.89, 0.5, 'Microsoft Windows Mobile 5.0 PocketPC', 1, 'LG Wink Plus GT350i', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung L310', 34627.33, 0.3, 'Feature phone', 5, 'Huawei Ascend Y600', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Lava V2 s', 17338.28, 0.1, 'Android 5.1.1', 2, 'Samsung E360', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Prestigio MultiPad 7.0 Prime +', 13682.21, 0.2, 'Android 4.0', 5, 'NEC N630', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Maxon MX-C20', 67973.46, 0.5, 'Feature phone', 4, 'LG T505', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Pantech Pursuit II', 68301.49, 0.4, 'Feature phone', 2, 'Amoi 2560', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Z140', 17498.46, 0.2, 'Feature phone', 3, 'Realme U1', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Orange Rono', 46605.71, 0.4, 'Android 4.4.2', 4, 'Asus Zenpad Z10 ZT500KL', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sony Ericsson Z550', 35006.72, 0.2, 'Feature phone', 2, 'Oppo U3', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Oppo Reno', 22605.22, 0.3, 'Android 9.0, up to Android 10, ColorOS 7.0', 5, 'BLU Life Play Mini', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Nokia 220 4G', 28079.21, 0.3, 'Feature phone', 1, 'Samsung Galaxy Ace S5830I', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Nokia 8.1 (Nokia X7)', 66910.47, 0.2, 'Android 9.0, up to Android 11, Android One', 5, 'Samsung Galaxy Fame Lite S6790', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung R730 Transfix', 42338.55, 0.5, 'Android 2.3', 1, 'Bird S890', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy Tab A 8.0 & S Pen (2015)', 16241.55, 0.5, 'Android 5.0', 5, 'Sony Ericsson Zylo', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Asus Zenpad 3S 10 Z500KL', 38832.22, 0.3, 'Android 6.0', 2, 'Samsung A100', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Motorola XOOM MZ601', 25616.28, 0.5, 'Android 3.0, 4.1.2, not up to 4.2', 2, 'Samsung R380 Freeform III', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Spice D-1111', 32095.4, 0.2, 'Microsoft Windows Mobile 6.0', 3, 'Dell Streak 7 Wi-Fi', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Google Pixel C', 38117.3, 0.1, 'Android 6.0.1, up to Android 8.0', 4, 'Nokia 8.1 Plus', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BlackBerry Curve 8980', 17048.63, 0.2, 'BlackBerry OS 5.0', 1, 'Ulefone Armor X6', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Wiko Y61', 64420.35, 0.1, 'Android 10', 4, 'T-Mobile G2 Touch', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Celkon A107', 10071.93, 0.2, 'Android 4.0', 3, 'Samsung T919 Behold', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Vodafone 340', 16362.15, 0.4, 'Feature phone', 3, 'Micromax Canvas Evok Power Q4260', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Pantech Vega R3 IM-A850L', 40520.1, 0.5, 'Android 4.0.4, up to 4.1', 2, 'Nokia 6270', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung B520', 36450.0, 0.3, 'Feature phone', 2, 'XOLO Q3000', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG MG295', 56274.08, 0.3, 'Feature phone', 3, 'Maxon MX-6805', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Prestigio MultiPad 7.0 Ultra + New', 54810.12, 0.2, 'Android 4.1', 2, 'Huawei U7510', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('AT&T Mustang', 57912.21, 0.2, 'Windows Mobile 6 Standard', 5, 'Motorola Moto C', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('alcatel Flash 2', 53678.88, 0.2, 'Android 5.1', 3, 'Micromax Bharat 5 Plus', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Oppo Reno5 4G', 18692.52, 0.5, 'Android 11, ColorOS 11.1', 4, 'LG Stylus 2', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('verykool R800', 15709.46, 0.3, 'Android 2.2', 4, 'Samsung i750', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Maxon MX-C180', 46966.03, 0.3, 'Feature phone', 3, 'Samsung T409', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Motorola M3288', 60279.55, 0.2, 'Feature phone', 4, 'NEC N21i', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('ZTE Blade S7', 68633.82, 0.4, 'Android 5.1, MiFavor UI', 2, 'Motorola W230', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy Core Lite LTE', 15962.19, 0.1, 'Android 4.3', 5, 'Energizer Hardcase H550S', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Huawei nova plus', 54892.0, 0.4, 'Android 6.0.1, EMUI 4.1', 5, 'BLU Grand X LTE', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Infinix Hot 5 Lite', 13312.71, 0.2, 'Android 7.0', 3, 'Nokia 3.1', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Siemens SXG75', 14263.45, 0.1, 'Feature phone', 5, 'Plum Ram 6', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('ZTE nubia Z5S mini NX403A', 60447.88, 0.3, 'Android 4.2.2', 3, 'Samsung M2510', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy Tab A 10.5', 11168.98, 0.5, 'Android 8.1, up to Android 10', 4, 'Philips 192', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Garmin-Asus A10', 37691.24, 0.3, 'Android 2.1', 3, 'Samsung Galaxy Note 10.1 N8010', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Tecno Camon 16 S', 62745.03, 0.5, 'Android 10, HIOS 6.2', 3, 'Nokia 6810', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Motorola A1260', 20715.05, 0.2, 'Android 1.6', 2, 'Sony Ericsson C901', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Blackview P6000', 28088.77, 0.5, 'Android 7.1.1', 2, 'Motorola MT917', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy Tab 8.9 P7310', 55893.18, 0.5, 'Android 3.0, up to 3.1', 5, 'Celkon C44 Duos', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Lenovo C2', 69757.33, 0.1, 'Android 6.0', 1, 'Samsung Galaxy S20 5G UW', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Plum Compass 2', 56672.7, 0.3, 'Android 6.0', 1, 'Yezz Andy A5 1GB', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Honor 9C', 39494.22, 0.5, 'Android 10, EMUI 10.1', 2, 'Google Pixel 4 XL', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BQ Aquaris X5 Plus', 46470.46, 0.3, 'Android 6.0.1, up to 7.1.1', 5, 'Plum Might Plus', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sony Ericsson T100', 33767.38, 0.3, 'Feature phone', 3, 'vivo S7t', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung S8000 Jet', 54139.88, 0.1, 'Feature phone', 2, 'Sony Ericsson W600', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Emporia Click Plus', 25828.88, 0.1, 'Feature phone', 1, 'LG F1200', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Hero', 64099.57, 0.4, 'Feature phone', 5, 'TCL Plex', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Bird SC24', 20724.06, 0.2, 'Feature phone', 2, 'Micromax X40', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung S5150 Diva folder', 14997.98, 0.1, 'Feature phone', 2, 'vivo V20 2021', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Micromax A310 Canvas Nitro', 59226.95, 0.3, 'Android 4.4.2', 4, 'Philips W635', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Vodafone Smart Tab II 10', 34896.46, 0.3, 'Android 4.0.3', 4, 'Samsung S5250 Wave525', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Realme Narzo 20 Pro', 67762.38, 0.5, 'Android 10, Realme UI', 5, 'Lenovo Vibe C', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG CF360', 43249.55, 0.1, 'Feature phone', 3, 'Philips X630', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('i-mobile 520', 33942.51, 0.3, 'Feature phone', 4, 'Micromax Bharat 2+', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Huawei Watch GT', 21592.89, 0.2, 'Proprietary OS', 2, 'Oppo A5s (AX5s)', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Studio G4', 68576.07, 0.3, 'Android 8.1 Oreo', 3, 'Yezz Andy 5.5M LTE VR', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sagem MY 3078', 44971.05, 0.5, 'Feature phone', 1, 'verykool i128', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('alcatel OT-C701', 59852.59, 0.2, 'Feature phone', 2, 'Acer Iconia Tab A100', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Dash', 61883.58, 0.1, 'Android 2.3', 5, 'Xiaomi Mi 11', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Vivo 5R', 66799.62, 0.4, 'Android 6.0', 5, 'Gigabyte GSmart G1362', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Lenovo Vibe K5', 51194.74, 0.3, 'Android 5.1', 4, 'Micromax Canvas Unite 4 Pro', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('QMobile Noir X950', 51925.14, 0.2, 'Android 4.4.2', 1, 'Samsung P705', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy Tab 4 8.0 (2015)', 59802.47, 0.4, 'Android 4.4.4', 5, 'Xiaomi Redmi K30 Pro Zoom', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Pantech PG-1400', 34293.35, 0.5, 'Feature phone', 5, 'Honor Magic', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Allview A5 Quad', 19853.84, 0.1, 'Android 4.2.2', 2, 'Orange Reyo', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('ZTE Open L', 43300.73, 0.2, 'Firefox OS 2.2', 3, 'Vodafone Smart first 6', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('alcatel OT-109', 18189.07, 0.5, 'Feature phone', 5, 'Samsung E1232B', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Apple Watch Edition 38mm (1st gen)', 34612.57, 0.1, 'watchOS 1.0, up to 4.3.2', 2, 'Lenovo Vibe Shot', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung E480', 60808.72, 0.3, 'Feature phone', 4, 'Honor 7', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sharp 930SH', 44786.63, 0.1, 'Feature phone', 4, 'Motorola Karma QA1', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Huawei P smart Pro 2019', 17197.68, 0.2, 'Android 9.0, EMUI 9.1', 2, 'HTC Desire 816G dual sim', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy M31 Prime', 21146.51, 0.2, 'Android 10, One UI 2.0', 5, 'Samsung Ativ Tab P8510', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Vertu Ascent', 31959.65, 0.1, 'Feature phone', 3, 'BlackBerry Curve 8300', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Energizer Energy 200', 37994.65, 0.5, 'Feature phone', 4, 'i-mate JASJAM', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG Optimus Big LU6800', 37900.71, 0.1, 'Android 2.2, up to 2.3', 4, 'Vertu Signature S', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Oppo Reno5 5G', 42273.42, 0.5, 'Android 11, ColorOS 11.1', 5, 'ZTE Axon Pro', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sony Xperia C3 Dual', 31622.0, 0.4, 'Android 4.4.2, up to 5.1', 3, 'Energizer Hardcase H500S', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Siemens C62', 37283.57, 0.3, 'Feature phone', 4, 'Sharp 934SH', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Amoi CA6', 32207.75, 0.5, 'Feature phone', 3, 'Philips Xenium 9@9m', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Vertu Constellation 2006', 32205.95, 0.5, 'Feature phone', 2, 'Asus Transformer Prime TF201', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Nokia 1662', 58663.73, 0.5, 'Feature phone', 2, 'Apple iPad Air 2', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sewon SG-2300CD', 10175.72, 0.5, 'Feature phone', 3, 'Samsung Serene', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Mitsubishi Trium Astral', 57312.0, 0.3, 'Feature phone', 1, 'Motorola RIZR Z8', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Plum Axe 4', 22561.97, 0.2, 'Android 6.0', 3, 'Panasonic GD67', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Plum Link II', 55135.45, 0.5, 'Android 4.2.2', 4, 'Samsung Galaxy Y Plus S5303', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG Watch W7', 49757.34, 0.4, 'Android Wear OS 2.0', 4, 'verykool i133', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BenQ-Siemens SL80', 17666.72, 0.4, 'Feature phone', 2, 'Asus Zenfone 4 (2014)', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('VK Mobile VK900', 65996.25, 0.5, 'Feature phone', 4, 'Philips W920', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG A258', 39564.34, 0.3, 'Feature phone', 1, 'Mitsubishi Trium Galaxy', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Samba Mini', 46778.22, 0.2, 'Feature phone', 2, 'Samsung Galaxy Tab 7.7 LTE I815', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Karbonn A9+', 67420.98, 0.5, 'Android 4.0', 1, 'Huawei Enjoy 9s', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('HP Pre 3 CDMA', 11584.94, 0.3, 'HP webOS 2.2', 2, 'Siemens CF62', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Siemens Xelibri 4', 30905.55, 0.1, 'Feature phone', 3, 'Honor Play 4T', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Siemens S10 active', 22887.4, 0.3, 'Feature phone', 4, 'Motorola MOTO ME525', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('ZTE Blade A410', 63003.44, 0.1, 'Android 5.1', 3, 'Vertu Ascent Ferrari GT', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Celkon C333', 53287.91, 0.5, 'Feature phone', 3, 'Panasonic Eluga Power', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Asus P526', 35375.35, 0.2, 'Microsoft Windows Mobile 6.0 Professional', 2, 'BLU Studio M HD', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Intercept', 26271.92, 0.2, 'Android 2.1, up to 2.2', 1, 'BLU Tango', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Studio View XL', 61253.57, 0.4, 'Android 7.0', 4, 'LG Harmony', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy Grand 2', 39915.4, 0.2, 'Android 4.3, up to 4.4.2', 3, 'LG Marquee LS855', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Realme Narzo 10', 13448.99, 0.1, 'Android 10, Realme UI', 2, 'Xiaomi Mi Note 10 Lite', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Micromax A100', 69063.21, 0.3, 'Android 4.0.3', 2, 'Samsung Galaxy Watch Active2', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Asus PadFone mini', 59865.16, 0.1, 'Android 4.3', 5, 'Lava A59', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Yezz Classic C30', 57451.64, 0.5, 'Feature phone', 4, 'Haier L1000', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG KC910 Renoir', 41433.67, 0.3, 'Feature phone', 4, 'ZTE Avail', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('ZTE Blade A7 Vita', 41884.77, 0.2, 'Android 8.1', 5, 'BenQ U700', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('ZTE X760', 50456.4, 0.1, 'Feature phone', 5, 'Xiaomi Mi Watch Lite', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Huawei Watch GT', 69326.4, 0.3, 'Proprietary OS', 3, 'Asus Zenpad 8.0 Z380C', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG KM386', 15864.79, 0.3, 'Feature phone', 5, 'Nokia 7270', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BlackBerry Curve 9320', 27108.0, 0.4, 'BlackBerry OS 7.1', 5, 'Samsung X140', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Amoi F99b', 66239.1, 0.5, 'Feature phone', 4, 'Motorola Z9', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Neo XT', 18110.87, 0.5, 'Feature phone', 5, 'Samsung J210', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung Galaxy Grand Prime', 31503.78, 0.1, 'Android 4.4.4', 5, 'BLU Studio 5.3', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Motorola CITRUS WX445', 51429.61, 0.5, 'Android 2.1', 1, 'Dell XCD35', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Ericsson GH 218', 21833.51, 0.1, 'Feature phone', 3, 'Gionee K3 Pro', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('ZTE Blade V9', 45461.41, 0.3, 'Android 8.1', 4, 'Lava X46', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Gionee S6 Pro', 60407.57, 0.4, 'Android 6.0.1, Amigo 3.2', 2, 'Telit t250', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Lenovo A6600 Plus', 48374.08, 0.2, 'Android 6.0', 2, 'Huawei nova 5', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Oppo A57', 31883.47, 0.2, 'Android 6, ColorOS 3', 5, 'Motorola Moto G9 (India)', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('alcatel 2052', 42543.1, 0.1, 'Feature phone', 1, 'Coolpad Modena 2', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('BLU Studio C Mini', 59485.38, 0.2, 'Android 4.4.2', 3, 'Plum Debut', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG GB110', 43251.03, 0.3, 'Feature phone', 5, 'BLU Studio C Super Camera', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Lava Iris X5', 66452.42, 0.1, 'Android 4.4.2', 1, 'BlackBerry Evolve', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Huawei Watch GT 2', 44480.59, 0.1, 'Proprietary OS', 4, 'NIU LIV 10', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Acer Iconia Tab A501', 28078.87, 0.1, 'Android 3.0, up to 3.2', 5, 'Nokia 8000 4G', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Celkon ARR35', 56323.08, 0.5, 'Feature phone', 2, 'T-Mobile Shadow', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Nokia E73 Mode', 51083.3, 0.3, 'Symbian OS 9.3, Series 60 v3.2 UI', 4, 'Ulefone Armor X8', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG C310', 53538.12, 0.3, 'Feature phone', 3, 'Maxwest Astro 3.5', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Maxon MX-C11', 30721.34, 0.3, 'Feature phone', 5, 'Nokia C1-00', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('HTC 10 evo', 14200.0, 0.2, 'Android 7.0', 4, 'Realme V5 5G', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Motorola v8088', 14849.22, 0.1, 'Feature phone', 3, 'Lava Iris 325 Style', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('HTC Desire 626s', 37514.35, 0.2, 'Android 5.1.1, up to 6.0.1, Sense UI 7', 5, 'NIU Niutek 3.5D', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung M110S Galaxy S', 45147.53, 0.1, 'Android 2.1, up to 2.3', 5, 'Spice Mi-1010 Stellar Pad', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Realme U1', 13697.09, 0.5, 'Android 8.1, up to Android 9.0, ColorOS 6', 5, 'Sharp GX10i', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Philips D908', 13184.0, 0.3, 'Microsoft Windows Mobile 6.5 Professional', 3, 'Huawei G7 Plus', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Samsung A777', 16954.53, 0.3, 'Feature phone', 1, 'Oppo A12s', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Nokia 5.1', 22654.22, 0.5, 'Android 8.0, up to Android 10, Android One', 2, 'Samsung Galaxy Tab Pro 10.1', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('verykool s505', 60463.95, 0.5, 'Android 4.2', 4, 'Yezz Ritmo 2 YZ420', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG GD710 Shine II', 45469.43, 0.2, 'Feature phone', 2, 'alcatel 1T 7', 2);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('LG Prada 3.0', 50893.92, 0.4, 'Android 2.3.7, up to 4.0', 3, 'Archos 50 Cobalt', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('i-mate Ultimate 6150', 14708.25, 0.3, 'Microsoft Windows Mobile 6.0 Professional', 4, 'Huawei Y6', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Lava Iris Atom X', 39004.3, 0.3, 'Android 4.4.2', 3, 'HP Pro Slate 10 EE G1', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Oppo R9 Plus', 63107.52, 0.4, 'Android 5.1, up to 6, ColorOS 3', 3, 'vivo X27 Pro', 1);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Sagem my301X', 64614.5, 0.4, 'Feature phone', 5, 'Huawei Ascend P7 mini', 3);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('i-mobile TV650 Touch', 47863.93, 0.4, 'Feature phone', 3, 'Sony Ericsson Z200', 4);
insert into Products (Name, Price, Discount, Description, Rating, Model, BrandId) values ('Huawei nova 5i', 40806.14, 0.5, 'Android 9.0, EMUI 9.1', 3, 'Motorola FLIPSIDE MB508', 2);
